### ISSUE TITLE
Cannot start tepkin on Heroku

### ISSUE THREAD

**Issue by malchmih** [fehmicansaglam/tepkin#19]
I had a failure today (it's the first time I use tepkin on Heroku)

```
2015-03-31T15:38:28.259453+00:00 app[web.1]: Oops, cannot start the server.
2015-03-31T15:38:28.261143+00:00 app[web.1]:    at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:105)
2015-03-31T15:38:28.261255+00:00 app[web.1]:    at net.fehmicansaglam.tepkin.MongoCollection$$anonfun$insert$2.apply(MongoCollection.scala:239)
2015-03-31T15:38:28.261353+00:00 app[web.1]:    at net.fehmicansaglam.tepkin.MongoCollection$$anonfun$insert$2.apply(MongoCollection.scala:236)
2015-03-31T15:38:28.261436+00:00 app[web.1]:    at scala.util.Success$$anonfun$map$1.apply(Try.scala:236)
2015-03-31T15:38:28.261532+00:00 app[web.1]:    at scala.util.Try$.apply(Try.scala:191)
2015-03-31T15:38:28.261628+00:00 app[web.1]:    at scala.util.Success.map(Try.scala:236)
2015-03-31T15:38:28.261720+00:00 app[web.1]:    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
2015-03-31T15:38:28.261823+00:00 app[web.1]:    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
2015-03-31T15:38:28.261901+00:00 app[web.1]:    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
2015-03-31T15:38:28.261995+00:00 app[web.1]:    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
2015-03-31T15:38:28.262117+00:00 app[web.1]:    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
2015-03-31T15:38:28.262217+00:00 app[web.1]:    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
2015-03-31T15:38:28.262315+00:00 app[web.1]:    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
2015-03-31T15:38:28.262422+00:00 app[web.1]:    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
2015-03-31T15:38:28.262522+00:00 app[web.1]:    at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
2015-03-31T15:38:28.260770+00:00 app[web.1]: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
2015-03-31T15:38:28.262623+00:00 app[web.1]:    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
2015-03-31T15:38:28.262732+00:00 app[web.1]:    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:401)
2015-03-31T15:38:28.262811+00:00 app[web.1]:    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
2015-03-31T15:38:28.262914+00:00 app[web.1]:    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
2015-03-31T15:38:28.263014+00:00 app[web.1]:    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
2015-03-31T15:38:28.263107+00:00 app[web.1]:    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I think it's somehow connected to http://stackoverflow.com/questions/20309758/updating-int-array-gets-converted-to-double-array-in-mongo-shell, but I'm not sure. Could you help?

**Comment by fehmicansaglam** [comment]
I guess I can. What is the version of MongoDB you are using?

**Comment by fehmicansaglam** [comment]
I have published an updated snapshot. Can you try again?

**Comment by DStranger** [comment]
Hello!
We are using mongo 2.6.9.
Unfortunately, this didn't help.

```
2015-03-31T17:06:19.112474+00:00 app[web.1]:    at scala.None$.get(Option.scala:345)
2015-03-31T17:06:19.112626+00:00 app[web.1]:    at scala.util.Success$$anonfun$map$1.apply(Try.scala:236)
2015-03-31T17:06:19.112580+00:00 app[web.1]:    at net.fehmicansaglam.tepkin.MongoCollection$$anonfun$insert$2.apply(MongoCollection.scala:236)
2015-03-31T17:06:19.111064+00:00 app[web.1]: Oops, cannot start the server.
2015-03-31T17:06:19.112713+00:00 app[web.1]:    at scala.util.Success.map(Try.scala:236)
2015-03-31T17:06:19.112673+00:00 app[web.1]:    at scala.util.Try$.apply(Try.scala:191)
2015-03-31T17:06:19.112854+00:00 app[web.1]:    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
2015-03-31T17:06:19.112434+00:00 app[web.1]:    at scala.None$.get(Option.scala:347)
2015-03-31T17:06:19.112829+00:00 app[web.1]:    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
2015-03-31T17:06:19.112960+00:00 app[web.1]:    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
2015-03-31T17:06:19.113101+00:00 app[web.1]:    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
2015-03-31T17:06:19.113065+00:00 app[web.1]:    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
2015-03-31T17:06:19.113153+00:00 app[web.1]:    at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
2015-03-31T17:06:19.112523+00:00 app[web.1]:    at net.fehmicansaglam.tepkin.MongoCollection$$anonfun$insert$2.apply(MongoCollection.scala:240)
2015-03-31T17:06:19.112765+00:00 app[web.1]:    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
2015-03-31T17:06:19.113007+00:00 app[web.1]:    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
2015-03-31T17:06:19.113216+00:00 app[web.1]:    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
2015-03-31T17:06:19.113481+00:00 app[web.1]:    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
2015-03-31T17:06:19.113274+00:00 app[web.1]:    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:401)
2015-03-31T17:06:19.112906+00:00 app[web.1]:    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
2015-03-31T17:06:19.113378+00:00 app[web.1]:    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
2015-03-31T17:06:19.113433+00:00 app[web.1]:    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
2015-03-31T17:06:19.113531+00:00 app[web.1]:    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2015-03-31T17:06:19.113330+00:00 app[web.1]:    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
2015-03-31T17:06:19.112213+00:00 app[web.1]: java.util.NoSuchElementException: None.get
```

**Comment by fehmicansaglam** [comment]
I see. But at least the error has changed. Mongo returns a different result than expected. I am investigating.

**Comment by fehmicansaglam** [comment]
That's really interesting. I have run all the tests towards MongoDB 2.6.9 and all pass. Anyway, I am updating the snapshot. Can you give it a try?

**Comment by fehmicansaglam** [comment]
I have created a sample application on Heroku. I hope it helps.

https://github.com/fehmicansaglam/tepkin-heroku
https://secret-citadel-5360.herokuapp.com/db

**Comment by malchmih** [comment]
I'm sorry, don't have time now. I'll look into it first thing tomorrow, ok?

**Comment by fehmicansaglam** [comment]
Sure.

**Comment by malchmih** [comment]
It worked when I added "authMechanism" part like you did. Thank you very much!

**Comment by fehmicansaglam** [comment]
No problem. We should actually define a default mechanism according to the
Mongo version.
