### ISSUE TITLE
Support conversion of nested map to BsonDocument

### ISSUE THREAD

**Issue by jeroenr** [fehmicansaglam/tepkin#24]
When I'm trying to convert a nested map to a BsonDocument using BsonDocument.from((String, Any)*). The signature accepts it, but I get a MatchError as result. See the following snippet

```
"Mongo driver" should "convert map to bson document" in {
    val map = Map("a" -> 1, "b" -> Map("c" -> "value"), "d" -> Seq("1","2"))
    BsonDocument.from(map.toIterable)
  }
```

which results in:

```
Map(c -> value) (of class scala.collection.immutable.Map$Map1)
scala.MatchError: Map(c -> value) (of class scala.collection.immutable.Map$Map1)
    at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:253)
    at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:251)
    at net.fehmicansaglam.bson.BsonDsl$BsonField$$anonfun$$colon$eq$1.applyOrElse(BsonDsl.scala:11)
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
    at net.fehmicansaglam.bson.BsonDocument$$anonfun$from$1.apply(BsonDocument.scala:82)
    at net.fehmicansaglam.bson.BsonDocument$$anonfun$from$1.apply(BsonDocument.scala:82)
```

**Comment by jeroenr** [comment]
See my proposal at fehmicansaglam/tepkin#25

**Comment by fehmicansaglam** [comment]
@jeroenr I have come up with a simpler implementation and updated 0.6-SNAPSHOT. Can you give it a try?

**Comment by jeroenr** [comment]
Looks good, except that it doesn't handle null values in a Map or List.

BsonDocument.from(Map("1" -> null)) fails with a MatchError i.e.

**Comment by fehmicansaglam** [comment]
Thanks. BsonNull implementation was already broken. I have fixed that. It also seems to work fine with collections now.
